# Production profile configuration
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # Enable second-level cache with Redis in production
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  # Redis cache for production
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

logging:
  level:
    root: WARN
    com.stacksmonitoring: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Stricter security for production
security:
  rate-limit:
    enabled: true
    requests-per-minute: 60
